global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'keycloak'
    static_configs:
      - targets: [ 'keycloak:8080' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka:8080' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'crm-service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    scheme: 'http'
    oauth2:
      client_id: 'prometheus'
      client_secret: 'MVD7sR6ZWgEXbHhVT9ja16WZbKjn0THE'
      token_url: 'http://keycloak:8080/realms/API_Gateway/protocol/openid-connect/token'
      endpoint_params:
        grant_type: client_credentials
    static_configs:
      - targets: [ 'crm-service:8081' ]
        labels:
          application: 'CRM_service'

  - job_name: 'ds-service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    scheme: 'http'
    oauth2:
      client_id: 'prometheus'
      client_secret: 'MVD7sR6ZWgEXbHhVT9ja16WZbKjn0THE'
      token_url: 'http://keycloak:8080/realms/API_Gateway/protocol/openid-connect/token'
      endpoint_params:
        grant_type: client_credentials
    static_configs:
      - targets: [ 'ds-service:8082' ]
        labels:
          application: 'DS_service'

  - job_name: 'cm-service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    scheme: 'http'
    oauth2:
      client_id: 'prometheus'
      client_secret: 'MVD7sR6ZWgEXbHhVT9ja16WZbKjn0THE'
      token_url: 'http://keycloak:8080/realms/API_Gateway/protocol/openid-connect/token'
      endpoint_params:
        grant_type: client_credentials
    static_configs:
      - targets: [ 'cm-service:8083' ]
        labels:
          application: 'CM_service'

  - job_name: 'an-service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    scheme: 'http'
    oauth2:
      client_id: 'prometheus'
      client_secret: 'MVD7sR6ZWgEXbHhVT9ja16WZbKjn0THE'
      token_url: 'http://keycloak:8080/realms/API_Gateway/protocol/openid-connect/token'
      endpoint_params:
        grant_type: client_credentials
    static_configs:
      - targets: [ 'an-service:8086' ]
        labels:
          application: 'AN_service'

#  - job_name: 'api-gw-service-metrics'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    scheme: 'http'
#    oauth2:
#      client_id: 'prometheus'
#      client_secret: 'MVD7sR6ZWgEXbHhVT9ja16WZbKjn0THE'
#      token_url: 'http://keycloak:8080/realms/API_Gateway/protocol/openid-connect/token'
#      endpoint_params:
#        grant_type: client_credentials
#    static_configs:
#      - targets: [ 'api-gw-service:8088' ]
#        labels:
#          application: 'API_GW_service'